### ISSUE TITLE
webserver handlers problem

### ISSUE THREAD

**Issue by Doctor-yoi** [NotArandomGUY/HuTao-GS#6]
Here is the log
![image](https://user-images.githubusercontent.com/106463935/186738418-05fe99e0-4147-46be-97be-e7b61ef6412b.png)

Just as the log,only webServer/handlers/Dispatch.js worked,I dont know why others didnt work

**Comment by NotArandomGUY** [comment]
are you using GC fiddler script? it's not compatible

**Comment by Doctor-yoi** [comment]
emm I use a application called mhyproxy maybe it was made for GC?

**Comment by Sycamore0** [comment]
> emm I use a application called mhyproxy maybe it was made for GC?

well,u should use dns mode
`米哈游代理转向` 可能确实是为gc打造的

**Comment by Doctor-yoi** [comment]
dns mode doesn’t work either

**Comment by Sycamore0** [comment]
> dns mode doesn’t work either

![null3104cba095ee1af4.jpg](https://user-images.githubusercontent.com/64587684/186788719-d2ebbb24-01d0-469e-ae77-5a8d00548c7e.jpg)

like this?

**Comment by Doctor-yoi** [comment]
Sorry I found the problem,I didn’t put the key in the right path😭
